source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'RxAsyncDisplayKit_Example' do
  pod 'RxAsyncDisplayKit', :path => '../'

  pod 'RxSwift', '~> 2.4'
  pod 'RxCocoa', '~> 2.4'
  pod 'RxBlocking', '~> 2.4'
  pod 'RxDataSources', '~> 0.6.2'
  pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :tag => '1.9.7.2', :inhibit_warnings => true
  

  target 'RxAsyncDisplayKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.9.2'
    pod 'Nimble', '~> 4.0.0'
  end
end
